# This file was generated by GoReleaser. DO NOT EDIT.
cask "nt" do
  version "0.29.0"

  on_macos do
    on_intel do
      sha256 "1ea946793e736de93bd6a0970ff7908887f811c7df9b7f764e691958e2e49864"
      url "https://github.com/navbytes/nt/releases/download/v#{version}/nt_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "7a0e80e2a47567e152fc775d0e06fff730e673bd6885e695030022ac07860378"
      url "https://github.com/navbytes/nt/releases/download/v#{version}/nt_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "94fd808d9020e2fc2f93c93be3359dbba3e4f8da79ae3efd0d3e920e009f1df6"
      url "https://github.com/navbytes/nt/releases/download/v#{version}/nt_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "17ce8ebb744c32add15ba621f021ff205d433c1d605dddb4cef4099447655baa"
      url "https://github.com/navbytes/nt/releases/download/v#{version}/nt_#{version}_linux_arm64.tar.gz"
    end
  end

  name "nt"
  desc "Terminal task & note manager — durable memory for AI coding sessions"
  homepage "https://github.com/navbytes/nt"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nt"

  # No zap stanza required

end
