# This file was generated by GoReleaser. DO NOT EDIT.
cask "nt" do
  version "0.28.0"

  on_macos do
    on_intel do
      sha256 "9f6c389f3251825e36fcf7d690ab8be07fb71cd4de535577df537126c32f36ac"
      url "https://github.com/navbytes/nt/releases/download/v#{version}/nt_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "db4471d59fde47c4b1033578eec44a223bba7cfe7b4bb532a5ec6385e6d4e3e3"
      url "https://github.com/navbytes/nt/releases/download/v#{version}/nt_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "182ac83b829d2c0adf96284da22e8f6eff82063f24cea09041b0375360adf390"
      url "https://github.com/navbytes/nt/releases/download/v#{version}/nt_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "98e243c78258c34c3fa92fb655471b3c34d08e4ac38c1fb75acee89e5e3da18f"
      url "https://github.com/navbytes/nt/releases/download/v#{version}/nt_#{version}_linux_arm64.tar.gz"
    end
  end

  name "nt"
  desc "Terminal task & note manager — durable memory for AI coding sessions"
  homepage "https://github.com/navbytes/nt"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nt"

  # No zap stanza required

end
