# This file was generated by GoReleaser. DO NOT EDIT.
cask "nt" do
  version "0.25.0"

  on_macos do
    on_intel do
      sha256 "c7012faa8355ce1edd5b3cc31283d8bdb71c1dd2e6c0120240104c26879d23b2"
      url "https://github.com/navbytes/nt/releases/download/v#{version}/nt_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "c5268f420da6c207e040644d28edcb3120fec9d09b491261122274d42f93fc58"
      url "https://github.com/navbytes/nt/releases/download/v#{version}/nt_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "eb4b4e3bc19a3fc189de0df30cf220a1b42001e2b53924f0ccc755d03906edd9"
      url "https://github.com/navbytes/nt/releases/download/v#{version}/nt_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "6952920d7628d49787df4c1b430803c14b4671df6fd0ec5ea668cc10c0a35ecd"
      url "https://github.com/navbytes/nt/releases/download/v#{version}/nt_#{version}_linux_arm64.tar.gz"
    end
  end

  name "nt"
  desc "Terminal task & note manager — durable memory for AI coding sessions"
  homepage "https://github.com/navbytes/nt"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nt"

  # No zap stanza required

end
