# Generated by navbytes/roost's release workflow — see
# scripts/update-homebrew-formula.sh there, which renders this file from the
# release's SHA256SUMS.txt. Edit that script, not this file.
class Roost < Formula
  desc "Session-native terminal multiplexer for AI agent CLIs"
  homepage "https://github.com/navbytes/roost"
  version "0.1.23"
  license "MIT"

  # `url`/`sha256` aren't permitted inside on_macos/on_linux blocks (brew
  # style: FormulaAudit/ComponentsOrder) — plain OS/CPU conditionals instead.
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/navbytes/roost/releases/download/v#{version}/roost-#{version}-aarch64-apple-darwin.tar.gz"
    sha256 "e15cc9f047af6f8ccb441e5f4d55175755bea82721fe631866a2466ca529d2a2"
  elsif OS.mac?
    url "https://github.com/navbytes/roost/releases/download/v#{version}/roost-#{version}-x86_64-apple-darwin.tar.gz"
    sha256 "c6e5f91f8945a534639b39413ebc016f6dafb222157ac899ec8be2417bff87cf"
  elsif OS.linux? && Hardware::CPU.arm?
    url "https://github.com/navbytes/roost/releases/download/v#{version}/roost-#{version}-aarch64-unknown-linux-gnu.tar.gz"
    sha256 "6b1011a0706d871ee7d67c4c3db57870500e2ab411b02c7d911a7833dbee323d"
  elsif OS.linux?
    url "https://github.com/navbytes/roost/releases/download/v#{version}/roost-#{version}-x86_64-unknown-linux-gnu.tar.gz"
    sha256 "9059092777af28cc8a3f5ce015d5105811b2307ce5ec05bf00611d2d76afe8de"
  end

  def install
    bin.install "roost"
  end

  test do
    assert_match "roost spawn ADAPTER", shell_output("#{bin}/roost --help 2>&1")
  end
end
