# Generated by navbytes/roost's release workflow — see
# scripts/update-homebrew-formula.sh there, which renders this file from the
# release's SHA256SUMS.txt. Edit that script, not this file.
class Roost < Formula
  desc "Session-native terminal multiplexer for AI agent CLIs"
  homepage "https://github.com/navbytes/roost"
  version "0.1.12"
  license "MIT"

  # `url`/`sha256` aren't permitted inside on_macos/on_linux blocks (brew
  # style: FormulaAudit/ComponentsOrder) — plain OS/CPU conditionals instead.
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/navbytes/roost/releases/download/v#{version}/roost-#{version}-aarch64-apple-darwin.tar.gz"
    sha256 "a63a291b59759af05d42c46cf7200058db281c9e2122716878d84a3c414162be"
  elsif OS.mac?
    url "https://github.com/navbytes/roost/releases/download/v#{version}/roost-#{version}-x86_64-apple-darwin.tar.gz"
    sha256 "3d5b778eddcf03c45700a55b80dfb6290edd9b0cd706c81fc843aa3022559595"
  elsif OS.linux? && Hardware::CPU.arm?
    url "https://github.com/navbytes/roost/releases/download/v#{version}/roost-#{version}-aarch64-unknown-linux-gnu.tar.gz"
    sha256 "1a82b298050a8119a8cb76b092ed6460e97a3a4d2ac67902123cad3b9d00dbe7"
  elsif OS.linux?
    url "https://github.com/navbytes/roost/releases/download/v#{version}/roost-#{version}-x86_64-unknown-linux-gnu.tar.gz"
    sha256 "adb62325c6f5da293947d9e3a19401eb27d5b200f58bb27d493055bf8a1f766a"
  end

  def install
    bin.install "roost"
  end

  test do
    assert_match "roost spawn ADAPTER", shell_output("#{bin}/roost --help 2>&1")
  end
end
